# Generated by Django 3.1.4 on 2021-08-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=150)),
                ('uage', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('accuracy_feed', models.IntegerField()),
                ('recommend_feed', models.IntegerField()),
                ('experience_feed', models.IntegerField()),
                ('msg_feed', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user_data',
                'managed': True,
            },
        ),
    ]
