# Generated by Django 3.1.4 on 2021-08-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210803_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='accuracy_feed',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='experience_feed',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='msg_feed',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='recommend_feed',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='uage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='uname',
            field=models.CharField(default='NULL', max_length=150),
        ),
    ]
