# Generated by Django 3.1.4 on 2021-08-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210803_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
