# Generated by Django 3.1.4 on 2021-08-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(default='NULL', max_length=150)),
                ('uage', models.IntegerField(default=0)),
                ('gender', models.CharField(default='NULL', max_length=10)),
                ('accuracy_feed', models.IntegerField(default=5)),
                ('recommend_feed', models.IntegerField(default=5)),
                ('experience_feed', models.IntegerField(default=5)),
                ('msg_feed', models.CharField(default='NULL', max_length=200)),
            ],
            options={
                'db_table': 'user_data',
                'managed': True,
            },
        ),
    ]
