# Generated by Django 3.1.4 on 2021-08-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='uname',
        ),
    ]
