# Generated by Django 3.1.4 on 2021-08-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_userdata_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='uname',
            field=models.CharField(default='NULL', max_length=150),
        ),
    ]
