# Generated by Django 3.1.4 on 2021-08-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210804_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_feed', models.IntegerField(default=5)),
                ('recommend_feed', models.IntegerField(default=5)),
                ('experience_feed', models.IntegerField(default=5)),
                ('msg_feed', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'feedback',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='accuracy_feed',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='experience_feed',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='msg_feed',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='recommend_feed',
        ),
    ]
