# Generated by Django 3.1.4 on 2021-08-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='uage',
            field=models.IntegerField(default=0),
        ),
    ]
